### ISSUE TITLE
ROOT5 / ROOT6 compatibility 

### ISSUE THREAD

**Issue by moukaddam** [adrien-matta/nptool#18]
The TSpectrum has changed the type of the returned position. See https://root.cern.ch/phpBB3/viewtopic.php?t=20802 for more details

in file /NPLib/Calibration/NPSiliconCalibrator.cxx the type of xpeaks must be changed if ROOT6 is in use:
ROOT5 compatible: Float_t* xpeaks =(Float_t*) sp->GetPositionX();
ROOT6 compatible: Double_t* xpeaks =(Double_t*) sp->GetPositionX();

**Comment by Munken** [comment]
Could you try the branch `calibration-fix`

**Comment by adrien-matta** [comment]
Worked on my system and an elegant solution proposed by Michael, so I merged it to the main branch.
