### ISSUE TITLE
Geometry Definitions

### ISSUE THREAD

**Issue by padsley** [adrien-matta/nptool#23]
This is more of a comment/request than a bug.

How is the geometry defined for detectors? There's the option to set R, theta, phi etc. and a 'Beta' which is probably the orientation of the system. How is this defined?

It would be good to have this in the guide somewhere.

P.S. I may have just missed this information but I'm in the middle of a nightshift and I have no idea what's happening anymore.

**Comment by adrien-matta** [comment]
That is true that it should be in the manual, but this is detector dependent, as each detector implementation comes with its requirement, and should there fore be in the corresponding detector manual, which is laking for most detector.

In most cases, the spherical coordinate placement make the detector facing lab frame origine. The beta values allow rotation of the detector around it's local reference axis (u,v,w). beta[0] rotate along the u axis, beta[1] around the v axis and beta[2] around the w axis. For a detector at 0 degrees, u would correspond to X, v to Y and w to Z in the lab frame (X,Y,Z).

**Comment by mustak21** [comment]
I have the coordinates of the centre of W1 detector with respect to the target.
Is the (R,THETA,PHI,BETA) token used for the centre of the detector?
