### ISSUE TITLE
Segfaults - currently for information only.

### ISSUE THREAD

**Issue by padsley** [adrien-matta/nptool#25]
This issue has been created for my own benefit so I have a place to store my thoughts. As you were.

I am currently getting a segmentation violation sometimes.

If I run a calculation with the same inputs, sometimes when I do /run/beamOn N, it crashes.

The culprit is Target::SlowDownBeam, which, when the fault occurs, is doing its first call using G4ParticleDefinition* (this is line 252 in Target.cc where `if(Beam->GetParticleName()=="neutron"` appears.

The failure always comes at the first event which makes me think that something is going wrong in the initialisation.

If I comment out that line (252), then the code fails further down. Yay.

The failure is not consistent - i.e. it doesn't always happen. If I re-run with the same input, things are working fine.

**Comment by padsley** [comment]
Also, looking at the outputs from the feedback from when the files are being read in, I see nothing different. (Saved as text files and used `diff`).

**Comment by adrien-matta** [comment]
Hi can you post the input file? I suspect you use an event generator with no beam, so the Beam pointer is not initialized and some time cause a segfault, sometime not.

**Comment by padsley** [comment]
Sorry for the random .tar.gz files but otherwise GH wouldn't let me dump them here.

Run with: ./npsimulation -E 19F3He.reaction -D 19F3He.detector -B batch.mac -O test

log.txt is how it should look and log_fail.txt is what happens when it faults (with the same command...)

log_fail2.txt is the terminal output that didn't make it through the pipe.
[log_fail2.txt](https://github.com/adrien-matta/nptool/files/964210/log_fail2.txt)


[log.txt](https://github.com/adrien-matta/nptool/files/964206/log.txt)
[log_fail.txt](https://github.com/adrien-matta/nptool/files/964208/log_fail.txt)



[SPAperture10Deg.txt](https://github.com/adrien-matta/nptool/files/964191/SPAperture10Deg.txt)
[19F3HeExDist.txt](https://github.com/adrien-matta/nptool/files/964179/19F3HeExDist.txt)
[19F3He.detector.tar.gz](https://github.com/adrien-matta/nptool/files/964185/19F3He.detector.tar.gz)
[19F3He.reaction.tar.gz](https://github.com/adrien-matta/nptool/files/964188/19F3He.reaction.tar.gz)

**Comment by padsley** [comment]
...I know that you're probably busy but have you managed to work out what's going on with this?

**Comment by adrien-matta** [comment]
Hi. 
I am finishing a rather big development and then I move on to test this. I think I will have some time for this Thursday.

Sorry for the delay.
Adrien.
