### ISSUE TITLE
Low Gain Energies in GeTAMU 

### ISSUE THREAD

**Issue by moukaddam** [adrien-matta/nptool#29]
@adrien-matta: @shuyaota is requesting to include High and Low-Gain energies simultaneously in GeTamuPhysics class. His argument is that Low- and High-Gain are equally important in 2 experiments of our campaign.
For now I have included distinct vectors in the GeTamuData class, i.e. by using the midas2nptool un-packer one can specify if he wants to read the Low-Gain channels (and the High-Gain) simultaneously from Midas, and store them in there specific vectors (parallel to the High-Gain ones). From thereon, the user can choose to call the Low- or the High-Gain in the Physics class. Obviously, the fact that the user have to manually choose the function names in not practical, especially when another collaborator updates the code. In contrast, the downside of adding another set of physics data for the Low-Gain (in parallel to the High-Gain ones) is that the Physics Class will loose its generic design.

Suggestion:
I can reconfigure the Physics class by adding an argument in the constructor of getamu (by default it will to use the High-Gain). The argument can go in the GeTamuData getter functions and can decide which Getter to use (High or Low). The same argument can be used upload the calibration tokens specific for the gain used. In this case the physics class is essentially the same, ant he user can call either gains from the project analysis.cxx 

 @adrien-matta What's your suggestion on that.

**Comment by adrien-matta** [comment]
Hi, 
The way we dealt with such cases in other detectors is by the used a "analysis config file" where the user can specify threshold, algorithm,... to be used during the analysis. Two good example are MUST2 where the analysis config file define the threshold, which are different for experiment and simulation, and if the energy is taken from the Ohmic or Junction side. CATS is also a very good example where the user can choose at run time which algorithm (gaussian, hyperbolic, baricentric) is used to get the position from the charge distribution.

The way its work is that there is a method called "ReadAnalysisConfig" which is called in the detector constructor. The method look for a config file located in config/configDETECTORNAME.txt . The input file is token based, just like the other nptool input file and option for analysis are loaded from there.

While it's a change I have not made yet, I would advice using the NPInputParser class to read the input file, which should simplify greatly the development of the method. 

The nice thing with this way of coding things, is that you can have a default case (ideally matching the simulation case) and then twerk the option at run time without the need for recompilation. The config file are also stored within the output tree, which guarantee traceability and reproducibility of the tree.

Let me know if you need further help to dev the methods.

**Comment by moukaddam** [comment]
Salut, 
This solution addresses all the problems, I'll let you know if further help is needed. 
Cheers.
