### ISSUE TITLE
Empty root file generated on analysis

### ISSUE THREAD

**Issue by kkabita** [adrien-matta/nptool#30]
I have a source run file. I am using the following command in NPTOOL to analyse the root file, the path to the root file is mentioned in "RunToTreat.txt".

npanalysis - D geometry _ filename . detector
                  - R runstotreatreat _ filename . txt
                  - O output _ rootfilename
This gives an empty root file in the nptool/Outputs/Analysis Folder. What can be the reasons of getting an empty root file?

**Comment by adrien-matta** [comment]
Hi,

What kind of run are you analysing? Is it from a simulation or from an experiment.
Also can you send the output of npanalysis. It should mention the number of event treated and how much data was written to the ouput file.

Regards,
Adrien.

**Comment by kkabita** [comment]
The run file is from the experiment e644. I can't attach the output file here due to its size. I am sending it to you by email.
Thank You.
