### ISSUE TITLE
Update an already installed NPTOOL

### ISSUE THREAD

**Issue by kkabita** [adrien-matta/nptool#31]
I have NPTOOL installed on the mac OS - Yosemite and I am using geant4 10.01.02. While running some simulation, I came across errors which imply missing of files, e.g. NPInputParser.h .
A complete set of commands for **updating** would be very helpful.

**Comment by adrien-matta** [comment]
Hi,

This look like you did make but not make install. Can you check that NPInputParser.h is present in NPLib/Core folder. If you run make install for NPLib, you should then have a copy of the file in NPLib/include. Then run make install for NPSimulation and the file should be found.
Alternatively you might have forgot to source nptool/nptool.sh

Cheers,
Adrien.

**Comment by kkabita** [comment]
Hi,

I did "make install" once again to be sure but still I can't find the "NPInputParser.h" file in any of the folders NPLib/Core or NPLib/Includes. 
Something that I think I should mention, I had tried to construct a few detectors and those files were giving errors while "make". So I removed those detector folders from NPLib/Detectors/ and then did "make -j4" and "make install".

**Comment by padsley** [comment]
> Something that I think I should mention, I had tried to construct a few detectors and those files were giving errors while "make".

That does sound like something important... is it possible for you to post the commands that you're running and the output so that we can see what's going wrong?

For updating from a Github repo, you should just need to do "git pull" and then recompile. Unless there's something odd which I don't know about .

**Comment by kkabita** [comment]
We use nptool in 3-4 computers in our lab, out of which one is mac OS- Yosemite and the others  CentOs 7. This problem(missing file) is occurring in only mac. 
When I am using the command "git pull", the output is:

 Dhrubas-MacBook-Pro:nptool dhruba$ git pull
remote: Counting objects: 188, done.
remote: Compressing objects: 100% (87/87), done.
remote: Total 188 (delta 158), reused 129 (delta 99), pack-reused 0
Receiving objects: 100% (188/188), 38.47 KiB | 19.00 KiB/s, done.
Resolving deltas: 100% (158/158), completed with 46 local objects.
From https://github.com/adrien-matta/nptool
   e1a13f7..be0ba53  NPTool.2.dev -> origin/NPTool.2.dev
Updating 3795728..be0ba53
error: Your local changes to the following files would be overwritten by merge:
Benchmarks/gaspard/ShowResults.C
Inputs/DetectorConfiguration/e644.detector
NPSimulation/Detectors/SSSD/CMakeLists.txt
NPSimulation/Detectors/SSSD/SSSD.cc
NPSimulation/Detectors/SSSD/SSSD.hh
NPSimulation/Detectors/SSSD/ThinSiScorers.cc
NPSimulation/Detectors/SSSD/ThinSiScorers.hh
NPSimulation/Detectors/W1/CMakeLists.txt
NPSimulation/Detectors/W1/W1.cc
NPSimulation/Detectors/W1/W1.hh
NPSimulation/Detectors/W1/W1Scorers.cc
NPSimulation/Detectors/W1/W1Scorers.hh
Projects/e644pd/Analysis.cxx
 Please, commit your changes or stash them before you can merge.
Aborting
Dhrubas-MacBook-Pro:nptool dhruba$ 


Now is there some different command to merge or I should follow the same procedure to compile, i.e., 
$npl
$cmake ./
$make -j4
$make install

**Comment by padsley** [comment]
Uh. Well, it appears that you've made some local modifications which are what the messages about 

> error: Your local changes to the following files would be overwritten by merge:

are about.

I think that first thing that we (or at least I) would like to see would be the output of doing

> $npl
> $cmake ./
> $make -j4
> $make install

Then we can see what point you're at now.

If you're only using some detectors, you can compile a limited subset, incidentally. It might be that if some of the detectors aren't compiling properly, you can work around that problem for now at least. (It is good to know if something isn't working, though.)

**Comment by kkabita** [comment]
The following commands run successfully without errors.
`$npl`
`$cmake ./`
`$make -j4`
`$make install`

But even after this, I checked the folder NPLib/Core, there is no NPInputParser.h

 Dhrubas-MacBook-Pro:Core dhruba$ ls
CMakeFiles NPLibVersion.h.in
NPVSpectra.cxx
CMakeLists.txt NPOnlineLinkDef.h
NPVSpectra.h
Makefile NPOptionManager.cxx
RootInput.cxx
NPAnalysisFactory.cxx NPOptionManager.h RootInput.h
NPAnalysisFactory.h NPPhysicalConstants.h
RootOutput.cxx
NPCalibrationManager.cxx NPSpectraServer.cxx RootOutput.h
NPCalibrationManager.h NPSpectraServer.h TAsciiFile.cxx
NPCoreLinkdef.h NPSystemOfUnits.h
TAsciiFile.h
NPDetectorFactory.cxx NPVAnalysis.cxx TAsciiFileDict.cxx
NPDetectorFactory.h NPVAnalysis.h
TAsciiFileDict.h
NPDetectorManager.cxx NPVDetector.cxx cmake_install.cmake
NPDetectorManager.h NPVDetector.h
icons
NPGlobalSystemOfUnits.h NPVDetectorDict.cxx
NPLibVersion.h NPVDetectorDict.h
Dhrubas-MacBook-Pro:Core dhruba$

**Comment by adrien-matta** [comment]
Hi,

What happen is that you edited some file that were changed as well on 
the server. So git does not know how to perform the update.

I am don't know what change you made and if they are to be kept or not.

You got two option:

1. This is the option I recommand, as it is non destructive. You rename 
your current nptool folder as nptool_old and do a git clone 
https://github.com/adrien-matta/nptool to get the last version of 
nptool. You can then try to reimport the relevant changes to the new nptool.

2. You can do a hard reset of the branch, but any change will be lost:

|>| |git fetch --all|

| > git reset --hard origin/NPTool.2.dev |

Cheers,

Adrien.

||_________________________________
*Dr Adrien Matta*
Chargé de Recherche CNRS
Groupe Structure Nucléaire
LPC Caen, ENSICAEN
6, Bd du Marechal Juin
14050 CAEN Cedex
France

**Comment by kkabita** [comment]
It is a little weird that there were no errors while doing "make" in the previous nptool but now as I renamed the old one and cloned the new, I got errors. I am attaching the error message in file, as the message is very long. The commands and errors are highlighted.


[error.docx](https://github.com/adrien-matta/nptool/files/1000975/error.docx)

**Comment by adrien-matta** [comment]
Hi,

I think this point to a problem with your root installation.

My guess is that you updated Mac OS X to Yosemite, and hence updated the 
version of the compiler CLANG. Unfortunately this means one have to 
reinstall root and geant4, because the name mangling convention changes, 
and the linker cannot properly link a library compiled with the old 
version against one compile with the new version.

Cheer,

Adrien.

_________________________________
*Dr Adrien Matta*
Chargé de Recherche CNRS
Groupe Structure Nucléaire
LPC Caen, ENSICAEN
6, Bd du Marechal Juin
14050 CAEN Cedex
France

**Comment by kkabita** [comment]
The update to Yosemite was done long before installation of Root, Geant4 and NPTOOL. The root version that I am using now is Root 5.34/32, I hope this is not a problem. I even checked recompiling geant4 examples, they are working fine.

**Comment by adrien-matta** [comment]
Hi,
The server is using 5.34/36 to test the build. So I don't think there is an issue here with the root version. it is however a linking error, but the undefined reference are from the libc, not from nptool, so I am bit perplex with what is causing the issue. 

The only time I saw this kind of error was after updating the compiler and the only way around was to recompile root.

**Comment by kkabita** [comment]
Hi,
I recompiled both geant4 and root. The error still remains the same.

**Comment by kkabita** [comment]
Hi,
Please let me know if there is any update. We need to make it working on the mac as soon as possible.
Thanks.

**Comment by padsley** [comment]
Is it possible that another programme is interferring with your NPTool compilation? I.e., that a path might not be set correctly? Have you checked that the environment variables are correct before you try compiling?

**Comment by kkabita** [comment]
The paths have been set correctly as it was working properly just before it had been cloned again. Did you check the error message that I have attached? @padsley

**Comment by padsley** [comment]
OK.

From what I can tell from a bit of Googling, this problem can sometimes occur when libraries were compiled with libstdc++ and can't be linked with libc++.

I'm going to guess that the problem would result from:

```
if(${CMAKE_CXX_COMPILER_ID} MATCHES ".*Clang.*")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Qunused-arguments -fcolor-diagnostics")
  if( UNIX AND NOT APPLE )
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libstdc++")
  endif()
  if( APPLE AND CLANG_VERSION_MAJOR VERSION_LESS 5 AND NOT nocpp11)
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")
  endif()
endif()
```
in

`/home/padsley/codes/nptool/NPLib/ressources/CMake/NPTool_CMake_Preamble.cmake`

However, not being a Mac user, the only thing I can suggest is maybe changing `-stdlib=libc++` to ` -stdlib=libstdc++` and seeing if that makes things work. (Or the other way around.) If it doesn't, then let me know and I'll come up with another random suggestion. :/

If it does work, let Adrien know.

**Comment by kkabita** [comment]
We updated the XCode 6.4 to 7.2.1 and installed Root 6 along. Now NPTool is working fine.
