### ISSUE TITLE
Energy loss in annularS1 

### ISSUE THREAD

**Issue by mustak21** [adrien-matta/nptool#32]
Hi,
Using a proton source of 40MeV I took annularS1,W1 and SSSD detectors each of thickness 500um.Although the energy deposited by the incoming protons on the W1 and SSSD detectors matches the values of energy loss as calculated by LISE++ but for annularS1 the value of energy deposited differs a lot. 

![annulars1](https://cloud.githubusercontent.com/assets/25579005/26098940/e89050b8-3a46-11e7-8360-7d5e73bbfabc.jpg)
![sssd](https://cloud.githubusercontent.com/assets/25579005/26098981/05d27b6a-3a47-11e7-9777-67724bc11851.jpg)
![w1](https://cloud.githubusercontent.com/assets/25579005/26098989/0c919490-3a47-11e7-9209-59c6005db940.jpg)

I checked the annularS1.hh file but couldn't identify the reason why the thickness appears to get doubled.

**Comment by adrien-matta** [comment]
Hi,
The full lenght was given as an argument in the G4Tubs constructor that take the half length, constructing a detector of twice the thickness. Thanks for noting the issue. It is fixed in the last commit.
