### ISSUE TITLE
Is multiple exit channels of a reaction allowed?

### ISSUE THREAD

**Issue by mustak21** [adrien-matta/nptool#33]
Hi,
I just wanted to know if it is allowed to edit the reaction file of a reaction such that there are multiple exit channels or does a single reaction can have only one exit channel?

**Comment by padsley** [comment]
I have no idea but I usually I just make different event generator files for the various exit channels and then chain together the TTrees from the resulting ROOT files and do my stuff from that.

Not sure if that's a useful suggestion but it works for me.

**Comment by mustak21** [comment]
Can you please elaborate the process of chaining together the TTrees of the root files of different reactions.I mean if you can give me some commands to do that.

**Comment by padsley** [comment]
Sure. I'm assuming for this point that you're just looking at the output of the simulation to give you an outline of what to do:

The TTree is called "SimulatedData", iirc.

Then you should be able to do:

TChain *vincula = new TChain("SimulatedData");

vincula->Add("Name_of_ROOT_file_1.root");
vincula->Add("Name_of_ROOT_file_2.root");

Then you can use the TChain object "vincula" as one would ordinarily use a TTree.

I must confess that I do not use the NPAnalysis functionality so I can't comment quite on how to use that. However, I assume that either it can be run on one ROOT file at a time to give an analysed output (which may be chained as above) or it can be run on multiple ROOT files and then combined into one large output file.

Does that make sense? I can try to find a code that I use which uses a TChain if you need but I hope that what I've said above works.

**Comment by adrien-matta** [comment]
To summarize: Lets imagine you want to simulate two reaction, you prepare two input file firstchannel.reaction and secondchannel.reaction, then you can do either:

**Method 1**: Run a single simulation, outputting a single root files using a geant4 macro.

Command (run in batch mode with no visualization, replace -B by -M to run with visualization):

    n**psimulation -D setup.detector -E firstchannel.reaction -B macro.mac**

macro.mac would look like this:

_/run/beamOn 10000
/gen/open secondchannel.reaction
/run/beamOn 10000_

**Method 2**: Run a simulation for each channel and chain them in napanalysis. This done using a run to treat file to build the input chain:

To run the simulation and then the analysis:

    **npsimulation -D setup.detector -E firstchannel.reaction -O firstChannel

    npsimulation -D setup.detector -E firstchannel.reaction -O secondChannel

    npanalysis -R RunToTreat.txt**

RunToTreat.txt file would look like this:

_TTreeName
    SimulatedTree
RootFileName
    ../../Outputs/Simulation/firstChannel.root
    ../../Outputs/Simulation/secondChannel.root_

Note that when analyzing a simulation, the input file can be omitted, in that case the input file use for to simulate the first root file of the list will be used.
