### ISSUE TITLE
checking nptool version 

### ISSUE THREAD

**Issue by mustak21** [adrien-matta/nptool#36]
How to check which version of NPTOOL I am using ?

**Comment by padsley** [comment]
If you downloaded with Git, go to the main directory and run:

`git branch -a`

The branch with the star next to it is the one that you're using.

**Comment by adrien-matta** [comment]
With the following command you get the exact commit number you are on, you can see all the commit number on git hub by clicking the commit link:
git rev-parse --short HEAD

Also there is a version number but it is incremented only for major changes. It appears at the beginnings when you run npa or nps.
