### ISSUE TITLE
nptool-wizard and NPVSpectra.h

### ISSUE THREAD

**Issue by robertshearman** [adrien-matta/nptool#40]
When creating a new detector, currently the make fails due to the GetHisto and GetCanvas functions derived from NPVSpectra.h.

The GetHisto function is commented in $NPL/core/NPVSpectra.h and the GetCanvas function is missing. (line 66).
in $NPL/Include/NPVSpectra.h these functions are present and uncommented. 
Un-commenting and adding in core allows for compilation, however I do not know if this is wanted/recommended and I haven't tested these functions. 

It should be noted that some detectors in the repo have simply commented out these functions.

**Comment by adrien-matta** [comment]
Fixed!
