### ISSUE TITLE
a simple Foil class

### ISSUE THREAD

**Issue by moukaddam** [adrien-matta/nptool#42]
With Sharc experiments (also potentially with Spice) we use passive foils as ion catchers or screens, mostly made of aluminum but could also be of other materials, . I didn't find one so I made it using nptool-wizard. 
Due to the "passive" purpose of this object, the spectra class was deleted since they are likely not to be used. I can also turn off the "sensitivity" but I figured out it might be useful in the future. 
@adrien-matta Let me know what you think about that, and whether you think it's worth it to add back the Histogram class.

This class can also be used in a plunger set-up.

Here's the possible configs:
------------------------------------
Foil
 POS = 0  0 250 mm
 Shape= Square
 Height= 40 mm
 Width= 40 mm
 Thickness= 10 micrometer
 Material= Al
%%%%%%%%%%%
Foil
 R= 350 mm
 THETA= 90 deg
 PHI= 63 deg
 Shape= Cylindrical
 Radius= 30 mm
 Thickness= 2 mm
 Material= Cu

**Comment by adrien-matta** [comment]
Hi.

I think it is a good idea! I don't see a trivial use to the spectra class, especially as it is filled during analysis and not during simulation... Is there a Physics Class associated? What is it doing? I would guess that having something similar to a plastic, with the energy deposit profile would be usefull. Maybe having the range as well for particle that stop.
