### ISSUE TITLE
Simulating Coincidence Sources

### ISSUE THREAD

**Issue by gchristian321** [adrien-matta/nptool#43]
I would like to simulate emission of multiple particles of the same type and different (but specific) energies from a source. For example, something like coincident 1173 keV and 1333 keV gamma-rays from 56Co.

Is there any way to do this that is already implemented in nptool? I couldn't find anything either in the documentation or by looking through the code. `EventGeneratorIsotropic` can do similar things, for example emit multiple particles in the same event, but they have to have the same energy or have random energies picked from the same range.

This is quite an easy feature to add, and in fact I've already done so in my version of the code. I did this by modifying `EventGeneratorIsotropic` such that all of the parameters related to particle emission are stored in vectors, which are looped over and the final particle is added to the `ParticleStack`. Different particles are specified in the configuration file, by adding a new `Isotropic` block.

I can check these changes in, of course, but before doing do, I wanted to make sure that 1) there isn't already the same feature available in nptool; and 2) that the way I have done things won't conflict with the intended way of using ``EventGeneratorIsotropic`.

**Comment by adrien-matta** [comment]
Hi Christian.

Actually you can, and there is two way to do it already.

Case 1 : For a know source, like 56Co: You need to check that you have a PhysicsListOption.txt file in the directory you are running the simulation (example file provided in the NPSimulation folder). In the file activate the radioactive decay options. Then in your event generator file, generate a Beam with 0 kinetic energy. The particle is produced at rest, and decayed by geant 4, this include, gamma, electron, positron, and neutron. The daughter nuclei can decay also is it is unstable. This is the technique we use to simulate the 152Eu spectra in the nptool paper. The main advantage is that Geant4 got the correct branching ratio for most current source, so it should relate directly to the experimental source spectrum.

Case 2: You want to simulate a decay, generally within a reaction: SImply define a gamma cascade with branching ratio in the GammaDecay event generator (see Example2)
