### ISSUE TITLE
Problem in NPTool installation

### ISSUE THREAD

**Issue by mustak21** [adrien-matta/nptool#48]
Hi,
I have successfully installed ROOT v6.10/06 and GEANT4.10.01.p02 in macOS X Yosemite 10.10.5
However while giving the command `cmake ./` in NPLib while installing NPTool I am getting the following error:

Dhrubas-MacBook-Pro:NPLib dhruba$ cmake ./

Looking for Root:

**Root /bin/sh: /Users/dhruba/root/bin/root-config: No such file or directory found**

Building all detectors

– Configuring done

– Generating done

– Build files have been written to: /Users/dhruba/nptool/NPLib

**Comment by padsley** [comment]
This sounds like a ROOT problem. In which the root-config binary can't be found.

ROOT on Macs can be odd. Check that echo $ROOTSYS returns the right path etc.

If you installed ROOT through Macports or whatever that's called you might have a problem as it doesn't install ROOT correctly for using ROOT things in other programmes.

**Comment by mustak21** [comment]
Since NPTool by default looks for ROOT in the same directory where it is installed so the issue is resolved when both of them were installed at the same directory.
