### ISSUE TITLE
Solid angle corresponding to each pixel.

### ISSUE THREAD

**Issue by mustak21** [adrien-matta/nptool#54]
Hi,
I am using 16x16 W1 detectors in my detector set up and I would like to calculate the solid angle subtended by each pixel of my individual telescopes. I need some guidance regarding which files I need to edit and modify in order to get the solid angles.

**Comment by adrien-matta** [comment]
Hi,

If you want to obtain the solid angle via Monte Carlo simulation, you need to divide the histogram of detected particle by the histogram of generated particle. If you want the solid angle of a single pixel, then you will need to put condition in the generation of the detected particle histogram.

The best way to achieve this is to build a dedicated Analysis project where you declare and fill in an histogram for each pixel of your setup and build a common histogram for all generated particle. You can use an isotropic source as the event generator. You can have a look at the SharcEfficiency project which is doing something similar.
