### ISSUE TITLE
Problem with Short-Lifetime Decays

### ISSUE THREAD

**Issue by gchristian321** [adrien-matta/nptool#55]
I've discovered a problem with the new way that decays are handled in nptool simulations. The mother nucleus for decays with a short lifetime ends up having a kinetic energy that is far below what it should be.

Within the file `Process/Decay.cc`, we have the following lines:

```
  double energy = PrimaryTrack->GetKineticEnergy();
  double time = PrimaryTrack->GetGlobalTime();

  // Randomize within the step
  // Assume energy loss is linear within the step
  // Assume no scattering
  double rand =  G4RandFlat::shoot(); 
  double length = rand*(m_PreviousLength); 
  energy += (1-rand)*(m_PreviousEnergy-energy); 
```

The intent is that the initial kinetic energy for the decay process is chosen randomly from within the step where the decay is supposed to happen. However, this causes a problem for very short lifetime decays, where the decay happens in the first step following the reaction that proceeds the decay.

When this happens, `PreviousEnergy` is equal to zero, and so the generated energy ends up being randomly distributed between 0 and the correct energy.

The easiest way I can think of to fix this is to have a check `if(PreviousEnergy > 0)` before doing the randomization (otherwise just leave `energy = PrimaryTrack->GetKineticEnergy();`). But maybe there is a more robust way, for example checking the step number or something like that.

**Comment by adrien-matta** [comment]
Hi Greg,

I can see where the issue come from. Can you provide your reaction file so I can look at what is the best possible implementation and make sure it does work. While the first solution you offer is simple and easy to implement I wonder if you can not end up with other issue in the case were the mother nuclei is at rest.

**Comment by gchristian321** [comment]
Hi Adrien,
Here is my reaction file (the `flat_ne21pt.txt` cross section file is just uniform from 0->30 deg and zero probability >30 deg).

```
Beam
 Particle= 21Ne
 ExcitationEnergy= 0 MeV
 Energy= 630 MeV
 SigmaEnergy= 1.08MeV
 SigmaThetaX= 0.01 deg
 SigmaPhiY= 0.01 deg
 SigmaX= 0.5 mm
 SigmaY=0.5 mm
 MeanThetaX= 0 deg
 MeanPhiY= 0 deg
 MeanX= 0 mm
 MeanY= 0 mm
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
TwoBodyReaction
 Beam= 21Ne
 Target= 1H
 Light= 3H
 Heavy= 19Ne
 ExcitationEnergyLight= 0.0 MeV
 ExcitationEnergyHeavy= 4.033 MeV
 CrossSectionPath= flat_ne21pt.txt  CSR
 ShootLight= 1
 ShootHeavy= 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Decay 19Ne
 Daughter= 15O 4He
 ExcitationEnergy= 0 0 MeV
 Threshold= 0 MeV
 DifferentialCrossSection= flat.txt particle4He
 BranchingRatio= 1.0
 LifeTime= 0 ns
 Shoot= 1 1
```

**Comment by adrien-matta** [comment]
Hi Greg,

I fixe the issue. It was actually not related to the life time, m_PreviousEnergy was never set to anything else than 0 in the constructor. I solved the issue by setting it in the Model Trigger method, where it should be. I don't have any physics test for this, and if you found the bug, I guess you do. Would you mind checking the solution make sense and then close the issue if it does?

Cheers,
Adrien.

**Comment by gchristian321** [comment]
Yes, I see now what the issue was.  Thanks for fixing.  I confirmed that my physics case is working well.
