### ISSUE TITLE
simulation of projectile breakup in NPTool

### ISSUE THREAD

**Issue by mustak21** [adrien-matta/nptool#57]
Hi,
I would like to know whether we can simulate projectile breakup in NPTool. Consider the reaction 

7Be + 12C -> 3He + 4He + 12C

where my projectile is 7Be and target is 12C.

How do the event generator file looks for simulating breakup reactions?

**Comment by mustak21** [comment]
I am attaching the event generator file that I am using for simulation. Kindly suggest if there is any mistake in it. After "run/beamOn" ,  it gives the message "starting run1" and just stop responding then (Please see the screenshots). I would really appreciate any help.

[Eventgenerator.txt](https://github.com/adrien-matta/nptool/files/4142288/Eventgenerator.txt)

![Screenshot from 2020-02-01 12-49-48](https://user-images.githubusercontent.com/25579005/73588630-704b1f80-44f1-11ea-877f-7b06ae198b4e.png)
![Screenshot from 2020-02-01 12-47-25](https://user-images.githubusercontent.com/25579005/73588632-704b1f80-44f1-11ea-82d9-782c090545af.png)

**Comment by adrien-matta** [comment]
Hello,

Thanks for your email. There seem to be no target volume in your geometry, do you defined one in your geometry? Without target volume the reaction and decay cannot occurs. If you want to perform a simulation without target effect put a thin target made of vacuum.

Also a Branching ratio of zero is not very good. If there is only one decay channel then it should be set to one. Let me know if this solves any of your issue.

Cheers,
Adrien.

**Comment by mustak21** [comment]
Hey Adrien!
Thanks a lot for replying. In the ".detector" file I am using a CD2 target and after setting the branching ratio to 1 I ran the simulation again but its again not responding. I am attaching the complete output after "run/beamOn".

[output.txt](https://github.com/adrien-matta/nptool/files/4142390/output.txt)

**Comment by padsley** [comment]
Hi,

Have you added print statements to the event generation? It might help you
to find where things are hanging up.


Dr Philip Adsley MA MSci (Cantab)
Claude Leon Postdoctoral Fellow
University of the Witwatersrand/iThemba LABS

**Comment by mustak21** [comment]
Hi,

The simulation is running fine for inelastic scattering of 7Be + 12C -> 7Be* + 12C
However,  when I am including the particle decay of 7Be into 4He and 3He it is not responding. Seems like something is wrong in the particle decay part in my event generator file.

As mentioned by Adrien I made the branching ratio to 1. But still it's the same. I need to know what are the following two parameters imply in the particle decay section, 

i) Threshold  ii) Lifetime

**Comment by adrien-matta** [comment]
Problem solved and commited on the new repository https://gitlab.in2p3.fr/np/nptool
