### ISSUE TITLE
Compilation Error and suggested fix

### ISSUE THREAD

**Issue by padsley** [adrien-matta/nptool#59]
I was downloading a new version of nptool to play with (it's a nice way to spend lockdown) and I noticed that the HELIOS detector system wasn't compiling.

Having done a bit of chasing, there needs to be a ClassDef statement added to THeliosPhysics.h, I think, but I'll leave it in the hands of someone who knows what they're doing.

**Comment by adrien-matta** [comment]
Hello Phil.
We moved the repository to the in2p3 gitlab, so the last version is to be found here:https://gitlab.in2p3.fr/np/nptool

Cheers,
Adrien.
