### ISSUE TITLE
Unit in input files

### ISSUE THREAD

**Issue by Munken** [adrien-matta/nptool#8]
This is something you need!

Feel free to use this implementation:  
https://git.kern.phys.au.dk/ausa/ausalib/blob/master/include/ausa/parser/UnitParser.h
https://git.kern.phys.au.dk/ausa/ausalib/blob/master/source/parser/UnitParser.cpp

**Comment by adrien-matta** [comment]
Fixed with last update. The input parser now support units. User is responsible for using unit that make sense though (putting an angle in mm will not crash or cause error).
